name: Upload Notebook and Generate MDX

on:
  push:
    paths:
      - "tutorials/**/*.ipynb"

jobs:
  process:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      COLAB_FOLDER_ID: 18xiVPIwYUAKJoSebzXO9c0aDLsH1hAc4

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib
          pip install nbconvert

      - name: Upload notebook to Colab folder
        id: upload_colab
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          AFTER_SHA="${{ github.sha }}"

          if ! git cat-file -e $BEFORE_SHA 2>/dev/null; then
            BEFORE_SHA=$(git rev-parse HEAD^)
          fi

          NOTEBOOK=$(git diff --name-only $BEFORE_SHA $AFTER_SHA | grep '\.ipynb$' | head -n 1)
          echo "NOTEBOOK=$NOTEBOOK" >> $GITHUB_ENV

          LINK=$(python upload_to_drive.py "$NOTEBOOK" --folder "$COLAB_FOLDER_ID")
          echo "colab_link=$LINK" >> "$GITHUB_OUTPUT"


      - name: Convert .ipynb ➜ Markdown
        run: |
          BASENAME="$(basename "$NOTEBOOK" .ipynb)"
          jupyter nbconvert "$NOTEBOOK" --to markdown --output "$BASENAME"

      - name: Build .mdx with Colab link
        run: |
          COLAB_LINK='${{ steps.upload_colab.outputs.colab_link }}'

          BASENAME="$(basename "$NOTEBOOK" .ipynb)"
          MARKDOWN_PATH="$(dirname "$NOTEBOOK")/$BASENAME.md"
          MDX_PATH="$(dirname "$NOTEBOOK")/$BASENAME.mdx"

          echo "<a href=\"$COLAB_LINK\" target=\"_blank\">Open in Colab</a>" > "$MDX_PATH"
          cat "$MARKDOWN_PATH" >> "$MDX_PATH"
